services:
  app:
    build: .
    container_name: ct9-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      SPRING_PROFILES_ACTIVE:
    networks:
      - app_network

networks:
  app_network:
    driver: bridge